/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.login.view;

import java.awt.event.KeyEvent;
import java.text.DecimalFormat;

/**
 *
 * @author isabe
 */
public class TelaVelocidadeMedia1 extends javax.swing.JFrame {

    /**
     * Creates new form TelaVelocidadeMedia
     */
    public TelaVelocidadeMedia1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        ButtonGResul = new javax.swing.JButton();
        msmBox = new javax.swing.JComboBox<>();
        distBox1 = new javax.swing.JComboBox<>();
        ValorTxtS = new javax.swing.JTextField();
        ValorTxtT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BoxResul = new javax.swing.JTextField();
        limparbutton = new javax.swing.JButton();
        voltarbutton = new javax.swing.JButton();
        medidafinalBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        saibamais = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FísicaProgramada.CalcVelocidadeMedia");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonGResul.setBackground(new java.awt.Color(0, 0, 0));
        ButtonGResul.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ButtonGResul.setForeground(new java.awt.Color(255, 255, 255));
        ButtonGResul.setText("GERAR RESULTADO");
        ButtonGResul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGResulActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonGResul, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 160, 40));

        msmBox.setBackground(new java.awt.Color(204, 204, 204));
        msmBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "h", "min", "segs" }));
        msmBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msmBoxActionPerformed(evt);
            }
        });
        msmBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                msmBoxKeyPressed(evt);
            }
        });
        getContentPane().add(msmBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 60, 30));

        distBox1.setBackground(new java.awt.Color(204, 204, 204));
        distBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "m", "km" }));
        distBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(distBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 60, 30));

        ValorTxtS.setBackground(new java.awt.Color(204, 204, 204));
        ValorTxtS.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ValorTxtS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorTxtSActionPerformed(evt);
            }
        });
        ValorTxtS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ValorTxtSKeyPressed(evt);
            }
        });
        getContentPane().add(ValorTxtS, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 210, 30));

        ValorTxtT.setBackground(new java.awt.Color(204, 204, 204));
        ValorTxtT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(ValorTxtT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 210, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 0, -1));

        BoxResul.setBackground(new java.awt.Color(204, 204, 204));
        BoxResul.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BoxResul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxResulActionPerformed(evt);
            }
        });
        getContentPane().add(BoxResul, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 153, 160, 30));

        limparbutton.setBackground(new java.awt.Color(0, 0, 0));
        limparbutton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        limparbutton.setForeground(new java.awt.Color(255, 255, 255));
        limparbutton.setText("LIMPAR");
        limparbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(limparbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 120, 40));

        voltarbutton.setBackground(new java.awt.Color(0, 0, 0));
        voltarbutton.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        voltarbutton.setForeground(new java.awt.Color(255, 255, 255));
        voltarbutton.setText("VOLTAR");
        voltarbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(voltarbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));

        medidafinalBox1.setBackground(new java.awt.Color(204, 204, 204));
        medidafinalBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "m/s", "km/h" }));
        getContentPane().add(medidafinalBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Tela da Velocidade Média (3).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 80, 60));

        jMenuBar1.setForeground(new java.awt.Color(204, 204, 204));

        jMenu4.add(jSeparator1);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-menu-arredondado-16.png"))); // NOI18N
        jMenu5.setText("Menu");
        jMenu5.add(jSeparator2);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-saída-de-emergência-24.png"))); // NOI18N
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);
        jMenu5.add(jSeparator3);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-visão-diurna-24.png"))); // NOI18N
        jMenu2.setText("Ir Para:");

        jMenuItem3.setText("Velocidade Média");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Temperatura");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Pesos em Astros");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenu5.add(jMenu2);

        saibamais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-decisão-24.png"))); // NOI18N
        saibamais.setText("Saiba mais");
        saibamais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saibamaisActionPerformed(evt);
            }
        });
        jMenu5.add(saibamais);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ValorTxtSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorTxtSActionPerformed
        
    }//GEN-LAST:event_ValorTxtSActionPerformed

    private void BoxResulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxResulActionPerformed
       
    }//GEN-LAST:event_BoxResulActionPerformed

    private void ButtonGResulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGResulActionPerformed
        try{
            DecimalFormat decimalFormat = new DecimalFormat("#.##");
            double distancia = Double.parseDouble(ValorTxtS.getText().replace(",", "."));
            String uniDistancia = (String) distBox1.getSelectedItem();
            double tempo = Double.parseDouble(ValorTxtT.getText().replace(",", "."));
             String uniTempo = (String) msmBox.getSelectedItem();
            double velocidadeMedia;
            String uniVel = (String) medidafinalBox1.getSelectedItem();
            
             if (uniDistancia.equals("m")) {
            distancia /= 1000; // Convertendo metros para quilômetros
        }

        if (uniTempo.equals("min")) {
            tempo /= 60; // Convertendo minutos para horas
        } else if (uniTempo.equals("segs")) {
            tempo /= 3600; // Convertendo segundos para horas
        }
          
            velocidadeMedia = distancia / tempo;
            
            if (uniVel.equals("m/s")){
                velocidadeMedia /= 3.6;
               BoxResul.setText((decimalFormat.format(velocidadeMedia) + " m/s")); 
            }
            else if(uniVel.equals("km/h")){
              BoxResul.setText((decimalFormat.format(velocidadeMedia) + " Km/H"));  
            }
            //BoxResul.setText("A velocidade Média será de: " + (decimalFormat.format(velocidadeMedia) + " Km/H"));
        } catch (NumberFormatException ex) {
            BoxResul.setText("Valores Inválidos");
    }                                            
     
    }//GEN-LAST:event_ButtonGResulActionPerformed

    private void msmBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msmBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msmBoxActionPerformed

    private void limparbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparbuttonActionPerformed
      ValorTxtS.setText("");
       ValorTxtT.setText("");
       BoxResul.setText("");
    }//GEN-LAST:event_limparbuttonActionPerformed

    private void voltarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarbuttonActionPerformed
         TelaSelecionar telasel = new TelaSelecionar();
        telasel.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarbuttonActionPerformed

    private void msmBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_msmBoxKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        ValorTxtS.requestFocus();
       }
    }//GEN-LAST:event_msmBoxKeyPressed

    private void ValorTxtSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ValorTxtSKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        ValorTxtT.requestFocus();
}
    }//GEN-LAST:event_ValorTxtSKeyPressed

    private void distBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_distBox1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaAgradecimento agrad = new TelaAgradecimento();
        agrad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        TelaVelocidadeMedia1 sel = new TelaVelocidadeMedia1();
        sel.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
TelaPesoPlanetas sel = new TelaPesoPlanetas();
        sel.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void saibamaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saibamaisActionPerformed
       SaibaMais2 sel = new SaibaMais2 ();
       sel.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_saibamaisActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       TelaTemperatura sel = new TelaTemperatura ();
       sel.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */ 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVelocidadeMedia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVelocidadeMedia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVelocidadeMedia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVelocidadeMedia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVelocidadeMedia1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BoxResul;
    private javax.swing.JButton ButtonGResul;
    private javax.swing.JTextField ValorTxtS;
    private javax.swing.JTextField ValorTxtT;
    private javax.swing.JComboBox<String> distBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JButton limparbutton;
    private javax.swing.JComboBox<String> medidafinalBox1;
    private javax.swing.JComboBox<String> msmBox;
    private javax.swing.JMenuItem saibamais;
    private javax.swing.JButton voltarbutton;
    // End of variables declaration//GEN-END:variables
}
