/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.login.view;

import java.text.DecimalFormat;

/**
 *
 * @author isabe
 */
public class TelaPesoPlanetas extends javax.swing.JFrame {

    /**
     * Creates new form TelaPesoPlanetas
     */
    public TelaPesoPlanetas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextPeso = new javax.swing.JTextField();
        ButtonResul = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        mercurio = new javax.swing.JTextField();
        venus = new javax.swing.JTextField();
        marte = new javax.swing.JTextField();
        jupiter = new javax.swing.JTextField();
        saturno = new javax.swing.JTextField();
        urano = new javax.swing.JTextField();
        netuno = new javax.swing.JTextField();
        lua = new javax.swing.JTextField();
        buttvoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        saibamais = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FísicaProgramada.PesoEmAstros");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextPeso.setBackground(new java.awt.Color(204, 204, 204));
        TextPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPesoActionPerformed(evt);
            }
        });
        getContentPane().add(TextPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 300, 30));

        ButtonResul.setBackground(new java.awt.Color(0, 0, 0));
        ButtonResul.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ButtonResul.setForeground(new java.awt.Color(255, 255, 255));
        ButtonResul.setText("GERAR RESULTADO");
        ButtonResul.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonResul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResulActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonResul, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 150, 40));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LIMPAR");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 160, 130, 40));

        mercurio.setBackground(new java.awt.Color(204, 204, 204));
        mercurio.setText(" ");
        mercurio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mercurioActionPerformed(evt);
            }
        });
        getContentPane().add(mercurio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 90, -1));

        venus.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(venus, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 90, -1));

        marte.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(marte, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 90, -1));

        jupiter.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jupiter, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 90, -1));

        saturno.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(saturno, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 80, -1));

        urano.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(urano, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 80, -1));

        netuno.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(netuno, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 80, -1));

        lua.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(lua, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 80, -1));

        buttvoltar.setBackground(new java.awt.Color(0, 0, 0));
        buttvoltar.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        buttvoltar.setForeground(new java.awt.Color(255, 255, 255));
        buttvoltar.setText("VOLTAR");
        buttvoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttvoltarActionPerformed(evt);
            }
        });
        getContentPane().add(buttvoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Tela do Peso em Astros.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenuBar1.setForeground(new java.awt.Color(204, 204, 204));

        jMenu4.add(jSeparator1);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-menu-arredondado-16.png"))); // NOI18N
        jMenu5.setText("Menu");
        jMenu5.add(jSeparator2);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-saída-de-emergência-24.png"))); // NOI18N
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);
        jMenu5.add(jSeparator3);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-visão-diurna-24.png"))); // NOI18N
        jMenu2.setText("Ir Para:");

        jMenuItem3.setText("Velocidade Média");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Temperatura");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Pesos em Astros");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenu5.add(jMenu2);

        saibamais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-decisão-24.png"))); // NOI18N
        saibamais.setText("Saiba mais");
        saibamais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saibamaisActionPerformed(evt);
            }
        });
        jMenu5.add(saibamais);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonResulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResulActionPerformed
         DecimalFormat decimalFormat = new DecimalFormat("#.#");
          double pesoin = Double.parseDouble(TextPeso.getText());
         double gravidadeMercurio = 3.7;
            double pesoMercurio = pesoin * gravidadeMercurio / 9.81;
            mercurio.setText(decimalFormat.format(pesoMercurio)+" Kg");
            
        double gravidadeVenus = 8.87;
            double pesoVenus = pesoin * gravidadeVenus / 9.81;
            venus.setText(decimalFormat.format(pesoVenus)+" Kg");
            
        double gravidadeMarte = 3.711;
            double pesoMarte = pesoin * gravidadeMarte / 9.81;
            marte.setText(decimalFormat.format(pesoMarte)+" Kg");
            
        double gravidadeJupiter = 24.79;
            double pesoJupiter = pesoin * gravidadeJupiter / 9.81;
            jupiter.setText(decimalFormat.format(pesoJupiter)+" Kg");
            
        double gravidadeSaturno = 10.44;
            double pesoSaturno = pesoin * gravidadeSaturno / 9.81;
            saturno.setText(decimalFormat.format(pesoSaturno)+" Kg");
            
        double gravidadeUrano = 8.69;
            double pesoUrano = pesoin * gravidadeUrano / 9.81;
            urano.setText(decimalFormat.format(pesoUrano)+" Kg");
            
        double gravidadeNetuno = 11.15;
            double pesoNetuno = pesoin * gravidadeNetuno / 9.81;
            netuno.setText(decimalFormat.format(pesoNetuno)+" Kg");
            
        double gravidadeLua =  0.17;
            double pesoLua = pesoin * gravidadeLua;
            lua.setText(decimalFormat.format(pesoLua)+" Kg");
            
           
    }//GEN-LAST:event_ButtonResulActionPerformed

    private void TextPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPesoActionPerformed

    private void mercurioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mercurioActionPerformed
         
    }//GEN-LAST:event_mercurioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         TextPeso.setText("");
          mercurio.setText("");
           venus.setText("");
            jupiter.setText("");
             urano.setText("");
              saturno.setText("");
               netuno.setText("");
                marte.setText("");
                 lua.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttvoltarActionPerformed
         TelaSelecionar telasel = new TelaSelecionar();
        telasel.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttvoltarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaAgradecimento agrad = new TelaAgradecimento();
        agrad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        TelaVelocidadeMedia1 sel = new TelaVelocidadeMedia1();
        sel.setVisible(true);
        dispose();

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        TelaTemperatura sel = new TelaTemperatura ();
        sel.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        TelaPesoPlanetas sel = new TelaPesoPlanetas();
        sel.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void saibamaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saibamaisActionPerformed
        SaibaMais2 sel = new SaibaMais2 ();
        sel.setVisible(true);
        dispose();
    }//GEN-LAST:event_saibamaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPesoPlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPesoPlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPesoPlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPesoPlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPesoPlanetas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonResul;
    private javax.swing.JTextField TextPeso;
    private javax.swing.JButton buttvoltar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTextField jupiter;
    private javax.swing.JTextField lua;
    private javax.swing.JTextField marte;
    private javax.swing.JTextField mercurio;
    private javax.swing.JTextField netuno;
    private javax.swing.JMenuItem saibamais;
    private javax.swing.JTextField saturno;
    private javax.swing.JTextField urano;
    private javax.swing.JTextField venus;
    // End of variables declaration//GEN-END:variables
}
